"""New metadata

Revision ID: 5fa40d6dcff3
Revises: 44e5ce0d61ef
Create Date: 2024-05-21 15:26:53.377482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa40d6dcff3'
down_revision: Union[str, None] = '44e5ce0d61ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
